# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='phone_number',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='display_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.CharField(default='', max_length=500),
        ),
    ]
