# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20170228_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
    ]
