# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_emailaddress_imagedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='imageData',
        ),
    ]
